//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sqlist.NET.Migration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sqlist.NET.Migration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No roadmap phases were found. This is likely due invalid assembly or path configurations..
        /// </summary>
        internal static string EmptyRoadmap {
            get {
                return ResourceManager.GetString("EmptyRoadmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialization failed due to invalid YAML format..
        /// </summary>
        internal static string InvalidYamlFormat {
            get {
                return ResourceManager.GetString("InvalidYamlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration service has not been initialized..
        /// </summary>
        internal static string MigrationNotInitialized {
            get {
                return ResourceManager.GetString("MigrationNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration phase has no guidelines defined..
        /// </summary>
        internal static string NoMigrationGuidelinesDefined {
            get {
                return ResourceManager.GetString("NoMigrationGuidelinesDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase title is required..
        /// </summary>
        internal static string PhaseTitleRequired {
            get {
                return ResourceManager.GetString("PhaseTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to identify the roadmap assembly. If no entry assembly is expected, the {0} option must be set..
        /// </summary>
        internal static string RoadmapAssemblyIsNull {
            get {
                return ResourceManager.GetString("RoadmapAssemblyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute scripts in resource &quot;{0}&quot;..
        /// </summary>
        internal static string ScriptExecutionFailed {
            get {
                return ResourceManager.GetString("ScriptExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to identify the scripts assembly. If no entry assembly is expected, the {0} option must be set..
        /// </summary>
        internal static string ScriptsAssemblyIsNull {
            get {
                return ResourceManager.GetString("ScriptsAssemblyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBMS with no default database are not supported..
        /// </summary>
        internal static string UnsupportedDatabase {
            get {
                return ResourceManager.GetString("UnsupportedDatabase", resourceCulture);
            }
        }
    }
}
