//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sqlist.NET.Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sqlist.NET.Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration to use..
        /// </summary>
        internal static string ConfigurationDescription {
            get {
                return ResourceManager.GetString("ConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force all dependencies to be resolved even if the last restore was successful..
        /// </summary>
        internal static string ForceDescription {
            get {
                return ResourceManager.GetString("ForceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target framework. Defaults to the first one in the project..
        /// </summary>
        internal static string FrameworkDescription {
            get {
                return ResourceManager.GetString("FrameworkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value has been provided for the handler project option..
        /// </summary>
        internal static string HandlerProjectNoValueException {
            get {
                return ResourceManager.GetString("HandlerProjectNoValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handler project option is null..
        /// </summary>
        internal static string HandlerProjectNullException {
            get {
                return ResourceManager.GetString("HandlerProjectNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the launch profile (if any) to use when launching the application. Launch profiles are defined in the launchSettings.json file and are typically called Development, Staging, and Production..
        /// </summary>
        internal static string LaunchProfileDescription {
            get {
                return ResourceManager.GetString("LaunchProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t build the project. Intended to be used when the build is up-to-date..
        /// </summary>
        internal static string NoBuildDescription {
            get {
                return ResourceManager.GetString("NoBuildDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t colorize output..
        /// </summary>
        internal static string NoColorDescription {
            get {
                return ResourceManager.GetString("NoColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t execute an implicit restore when running the command..
        /// </summary>
        internal static string NoRestoreDescription {
            get {
                return ResourceManager.GetString("NoRestoreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix output with level..
        /// </summary>
        internal static string PrefixDescription {
            get {
                return ResourceManager.GetString("PrefixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process is already running..
        /// </summary>
        internal static string ProcessAlreadyRunningException {
            get {
                return ResourceManager.GetString("ProcessAlreadyRunningException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the startup project file..
        /// </summary>
        internal static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target runtime to bundle for..
        /// </summary>
        internal static string RuntimeDescription {
            get {
                return ResourceManager.GetString("RuntimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show verbose output..
        /// </summary>
        internal static string VerboseDescription {
            get {
                return ResourceManager.GetString("VerboseDescription", resourceCulture);
            }
        }
    }
}
